# Message sending time. (required)
builtin_interfaces/Time stamp

# Operation mode API operation mode. (required)
uint32 operation_mode

# Operation mode API autoware control. (required)
uint32 platform_mode

# MRM request API strategy. (required)
uint32 mrm_strategy

# MRM request API behavior. (required)
uint32 mrm_behavior

# Target mode returned by the decision logic. (required)
uint32 autoware_mode

# Transitioning to initial mode. (required)
bool initializing

# Transitioning to target mode. (required)
bool transitioning

# Modes that failed to transition. (required)
uint32[] unavailable_modes
