/**:
  ros__parameters:
    segmentation3d:
      dec_depths: [0, 0, 1, 1]
      class_names: [
          "car",
          "truck",
          "bus",
          "motorcycle",
          "bicycle",
          "pedestrian",
          "animal",
          "barrier",
          "traffic_cone",
          "debris",
          "driveable_flat",
          "non_driveable_flat",
          "vegetation",
          "manmade",
          "vertical_thin",
          "noise",
        ]
      palette: [
        0, 150, 245,    # Blue - car
        160, 32, 240,   # Purple - truck
        255, 255, 0,    # Yellow - bus
        255, 105, 180,  # Hot Pink - motorcycle
        255, 192, 203,  # Pink - bicycle
        255, 0, 0,      # Red - pedestrian
        173, 255, 47,   # Green Yellow - animal
        255, 127, 0,    # Orange - barrier
        255, 240, 150,  # Light Yellow - traffic_cone
        255, 0, 255,    # Magenta - debris
        139, 137, 137,  # Grey - driveable_flat
        139, 137, 137,  # Grey - non_driveable_flat
        0, 175, 0,      # Green - vegetation
        230, 230, 250,  # Lavender - manmade
        153, 50, 204,   # Dark Orchid - vertical_thin
        64, 224, 208,   # Turquoise - noise
      ]
