/**:
  ros__parameters:
    input_topics: [
      "/sensing/lidar/front_upper/pointcloud_raw_ex",
      "/sensing/lidar/front_lower/pointcloud_raw_ex",
      "/sensing/lidar/left_upper/pointcloud_raw_ex",
      "/sensing/lidar/left_lower/pointcloud_raw_ex",
      "/sensing/lidar/right_upper/pointcloud_raw_ex",
      "/sensing/lidar/right_lower/pointcloud_raw_ex",
      "/sensing/lidar/rear_upper/pointcloud_raw_ex",
      "/sensing/lidar/rear_lower/pointcloud_raw_ex"
    ]
    input_offset: [0.025, 0.025, 0.01, 0.0, 0.05, 0.05, 0.05, 0.05]
    timeout_sec: 0.075
    output_frame: base_link
    input_twist_topic_type: twist