/**:
  ros__parameters:
    maximum_queue_size: 5
    timeout_sec: 0.5
    offset_tolerance: 0.03
    is_motion_compensated: true
    publish_synchronized_pointcloud: true
    keep_input_frame_in_synchronized_pointcloud: true
    synchronized_pointcloud_postfix: pointcloud
    input_twist_topic_type: twist
    input_topics: [
                    "/sensing/lidar/right/pointcloud_before_sync",
                    "/sensing/lidar/left/pointcloud_before_sync",
                    "/sensing/lidar/top/pointcloud_before_sync"
                ]
    output_frame: base_link
    lidar_timestamp_offsets: [0.0, 0.03, 0.04]
