/**:
  ros__parameters:
    rois_timestamp_offsets: [0.06167, 0.011167, 0.045, 0.02833, 0.07833, 0.095]
    timeout_sec: 0.070
    # match_threshold_ms: 50.0
    image_buffer_size: 15
    # projection setting for each ROI whether unrectify image
    point_project_to_unrectified_image: [false, false, false, false, false, false]
    debug_mode: false
    filter_scope_min_x: -100.0
    filter_scope_min_y: -100.0
    filter_scope_min_z: -100.0
    filter_scope_max_x: 100.0
    filter_scope_max_y: 100.0
    filter_scope_max_z: 100.0

    # camera cache setting for each ROI
    approximate_camera_projection: [true, true, true, true, true, true]
    # grid size in pixels
    approximation_grid_cell_width: 1.0
    approximation_grid_cell_height: 1.0

    # debug parameters
    publish_processing_time_detail: false
    matching_strategy:
      type: advanced
      det3d_noise_window: 0.01
      rois_timestamp_noise_window: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005]
